Revert GooglePlayServices version wildcard. It turns out GPS 5.0.77 had a critical bug and so they pulled it.
From: http://tools.android.com/knownissues

“
Google Play Services 5.0.77
If your builds suddenly stop working with this error message:
  Error: Failed to find: com.google.android.gms:play-services:5.0.77
this is caused by the play services artifact being removed from the local Google Maven repository because it contained some critical bugs. It was been replaced by version 5.0.89 instead. (More information)
“